version: '3'

services:
  api:
    container_name: transfer_system_api
    depends_on:
      mysql-db:
        condition: service_healthy
    build:
      dockerfile: Dockerfile
    env_file: .env
    environment:
      - MYSQL_URL=jdbc:mysql://mysql-db:${MYSQL_PORT:-3306}/${MYSQL_NAME:-transfer_system}
      - MYSQL_USERNAME=${MYSQL_USERNAME:-root}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD:-root}
      - ACTIVE_MQ_BROKER_URL=tcp://active-mq:${ACTIVE_MQ_BROKER_PORT:-61616}
    ports:
      - ${API_LOCAL_PORT:-8081}:${API_DOCKER_PORT:-8080}
    networks:
      - transfer-system-network
      #- nexus_nexus-network
  mysql-db:
    container_name: transfer_system_mysqldb
    image: mysql:8.0.32
    env_file: .env
    environment:
      - MYSQL_DATABASE=${MYSQL_NAME:-transfer_system}
      - MYSQL_ROOT_PASSWORD=${MYSQL_PASSWORD:-root}
    ports:
      - ${MYSQL_PORT:-3306}:${MYSQL_PORT:-3306}
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 7s
      retries: 3
    networks:
      - transfer-system-network
  active-mq:
    container_name: transfer_system_activemq
    image: rmohr/activemq:5.15.9-alpine
    ports:
      - 61616:61616
      - 8161:8161
    volumes:
      - activemq-data:/data/activemq
      - activemq-log:/var/log/activemq
    networks:
      - transfer-system-network

volumes:
  mysql-data:
  activemq-data:
  activemq-log:

networks:
  transfer-system-network:
  #nexus_nexus-network:
  #  external: true