spring:
  activemq:
    user: ${ACTIVE_MQ_USERNAME:admin}
    password: ${ACTIVE_MQ_PASSWORD:admin}
    packages:
      trusted: com.nordea.iovchuk.transfer_system.entity
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

active-mq:
  transfer:
    request:
      queue: ${TRANSFER_REQUEST_MQ:transfer_request_mq}
    response:
      queue: ${TRANSFER_RESPONSE_MQ:transfer_response_mq}