spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    properties:
      hibernate:
        generate_statistics: false
        show_sql: true

logging:
  level:
    org:
      hibernate:
        type: trace