name: tests
run-name: ${{ github.actor }} Tests check

on:
  pull_request:
    branches: [ "master" ]

jobs:
  #Unit tests
  unit-tests:
    strategy:
      matrix:
        os: [ ubuntu-22.04 ]
        experimental: [ false ]
        include:
          - os: windows-2022
            experimental: true
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: temurin
          cache: maven
      - name: Check repos and services tests
        run: mvn surefire:test
    continue-on-error: ${{ matrix.experimental }}
  #Integration tests
  integration-tests:
    strategy:
      matrix:
        os: [ ubuntu-22.04 ]
        experimental: [ false ]
        include:
          - os: windows-2022
            experimental: true
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: temurin
          cache: maven
      - name: Check integration tests
        run: mvn failsafe:integration-test
    continue-on-error: ${{ matrix.experimental }}


  #docker-up:
  #  runs-on: self-hosted-vm
  #  needs: [unit-tests, integration-tests]
  #  steps:
  #    - uses: actions/checkout@v3
  #    - name: Docker compose up
  #      run: sudo docker compose up -d --build
