name: tests
run-name: ${{ github.actor }} Tests check

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  unit-tests:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: temurin
          cache: maven
      - name: Check repos and services tests
        run: mvn test -Dtest="*RepositoryTest, *ServiceTes*"
  integration-tests:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: temurin
          cache: maven
      - name: Check integration tests
        run: mvn test -Dtest="*IntegrationTest"
  #docker-up:
  #  runs-on: self-hosted-vm
  #  needs: [unit-tests, integration-tests]
  #  steps:
  #    - uses: actions/checkout@v3
  #    - name: Docker compose up
  #      run: sudo docker compose up -d --build
