name: tests
run-name: ${{ github.actor }} Tests check

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  unit-tests:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: temurin
          cache: maven
      - name: mvn test repos and services
        run: mvn test -Dtest="*RepositoryTest, *ServiceTes*"
  integration-tests:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: temurin
      - name: mvn integration test
        run: mvn test -Dtest="*IntegrationTest"
